//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirmalar
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Yetkili { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Sektor { get; set; }
        public Nullable<int> il { get; set; }
        public Nullable<int> ilce { get; set; }
        public string Adres { get; set; }
    }
}
