//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullanicilar
    {
        public int ID { get; set; }
        public string KullaniciAd { get; set; }
        public string Parola { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual TblPersonel TblPersonel { get; set; }
    }
}
