//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lookupEditKullanimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevamsizlikTablosu
    {
        public int devamsizlik_id { get; set; }
        public string tc { get; set; }
        public string devamsizlik_gunu { get; set; }
    }
}
