//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lookupEditKullanimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsBilgiTabloDetay
    {
        public string Kod { get; set; }
        public string UrunKod { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> AlisAdet { get; set; }
        public Nullable<double> AlisFiyat { get; set; }
    }
}
