//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lookupEditKullanimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsBilgiTablo
    {
        public string Kod { get; set; }
        public string Tarih { get; set; }
        public string BaslamaSaat { get; set; }
        public string BitisSaat { get; set; }
        public string Tanim { get; set; }
        public string MusteriTC { get; set; }
        public string isYapanTC { get; set; }
    }
}
