//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lookupEditKullanimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelTablosu
    {
        public string tc { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public string tel { get; set; }
        public string kayit_tarihi { get; set; }
        public Nullable<double> maas { get; set; }
    }
}
