//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gridControlVeriCekme
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCAEntities : DbContext
    {
        public SCAEntities()
            : base("name=SCAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalismaTablo> CalismaTabloes { get; set; }
        public virtual DbSet<DevamsizlikTablosu> DevamsizlikTablosus { get; set; }
        public virtual DbSet<GirisTablosu> GirisTablosus { get; set; }
        public virtual DbSet<IsBilgiTablo> IsBilgiTabloes { get; set; }
        public virtual DbSet<PersonelTablosu> PersonelTablosus { get; set; }
        public virtual DbSet<StokTablo> StokTabloes { get; set; }
        public virtual DbSet<IsBilgiTabloDetay> IsBilgiTabloDetays { get; set; }
        public virtual DbSet<ilceler> ilcelers { get; set; }
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<MusteriTablosu> MusteriTablosus { get; set; }
    }
}
