//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gridControlVeriCekme
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTablosu
    {
        public string tcno { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string cep_telefonu { get; set; }
        public string ev_telefonu { get; set; }
        public string eposta { get; set; }
        public string ev_adresi { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> arsiv { get; set; }
    }
}
