//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gridControlVeriCekme
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokTablo
    {
        public string UrunKodu { get; set; }
        public string UrunAd { get; set; }
        public string UrunKategori { get; set; }
        public Nullable<double> UrunFiyat { get; set; }
        public Nullable<int> UrunAdet { get; set; }
        public string aciklama { get; set; }
    }
}
