using DevExpress.Utils.Design;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace PlaceEditorRepositoryKullanimi
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSource1.Fill();
        }

        private void repositoryItemButtonEdit1_Click(object sender, EventArgs e)
        {
            Console.WriteLine("Çalışıyor...");
        }

        private void Form1_Load(object sender, EventArgs e)
        {
        }
    }
}
