using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace ExportToXKullanimi
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSource1.Fill();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void simpleButton6_Click(object sender, EventArgs e)
        {
           
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            gridView1.ExportToPdf(@"test6.pdf");
           /* string find = string.Concat("test5", ".pdf");
            Process.Start("Acrobat.exe", find);*/
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            gridView1.ExportToXlsx("exceldosyam1.xlsx");
            string find = string.Concat("exceldosyam1", ".xlsx");
            Process.Start("Acrobat.exe", find);//Excel olarak değiştirilecek
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
        }
    }
}
