//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ratingControlKullanimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Filmler
    {
        public short FilmID { get; set; }
        public string FilmAd { get; set; }
        public string FilmTur { get; set; }
        public Nullable<double> FilmPuan { get; set; }
        public Nullable<bool> FilmKategori { get; set; }
        public string FilmResim { get; set; }
    }
}
